"""01

Revision ID: 515a6ad2f07c
Revises: c746c11aaed1
Create Date: 2022-05-11 12:11:14.408332

"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision = '515a6ad2f07c'
down_revision = 'c746c11aaed1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('condominio',
    sa.Column('id_condominio', sa.Integer(), nullable=False),
    sa.Column('denominazione', sa.String(length=256), nullable=True),
    sa.Column('indirizzo', sa.String(length=256), nullable=True),
    sa.Column('cf', sa.String(length=16), nullable=True),
    sa.Column('piva', sa.String(length=11), nullable=True),
    sa.PrimaryKeyConstraint('id_condominio'),
    schema='sue'
    )
    op.create_index(op.f('ix_sue_condominio_id_condominio'), 'condominio', ['id_condominio'], unique=False, schema='sue')
    op.create_table('esecutore',
    sa.Column('app', sa.String(length=256), nullable=True),
    sa.Column('nome', sa.String(length=256), nullable=True),
    sa.Column('cognome', sa.String(length=256), nullable=True),
    sa.Column('cf', sa.String(length=16), nullable=True),
    sa.Column('piva', sa.String(length=11), nullable=True),
    sa.Column('data_nato', sa.Date(), nullable=True),
    sa.Column('comune_nato', sa.String(length=256), nullable=True),
    sa.Column('prov_nato', sa.String(length=2), nullable=True),
    sa.Column('loc_nato', sa.String(length=256), nullable=True),
    sa.Column('codcat_nato', sa.String(length=4), nullable=True),
    sa.Column('cittadinanza', sa.String(length=256), nullable=True),
    sa.Column('sesso', sa.String(length=1), nullable=True),
    sa.Column('comune', sa.String(length=256), nullable=True),
    sa.Column('prov', sa.String(length=2), nullable=True),
    sa.Column('loc', sa.String(length=256), nullable=True),
    sa.Column('cap', sa.String(length=5), nullable=True),
    sa.Column('indirizzo', sa.String(length=256), nullable=True),
    sa.Column('civico', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('pec', sa.String(length=256), nullable=True),
    sa.Column('telefono', sa.String(length=256), nullable=True),
    sa.Column('cellulare', sa.String(length=256), nullable=True),
    sa.Column('fax', sa.String(length=256), nullable=True),
    sa.Column('id_esecutore', sa.Integer(), nullable=False),
    sa.Column('denominazione', sa.String(length=256), nullable=True),
    sa.Column('sede_comune', sa.String(length=256), nullable=True),
    sa.Column('sede_prov', sa.String(length=2), nullable=True),
    sa.Column('sede_cap', sa.String(length=5), nullable=True),
    sa.Column('sede_indirizzo', sa.String(length=256), nullable=True),
    sa.Column('sede_civico', sa.String(length=50), nullable=True),
    sa.Column('cciaa', sa.String(length=256), nullable=True),
    sa.Column('cciaa_numero', sa.String(length=256), nullable=True),
    sa.Column('inps', sa.String(length=256), nullable=True),
    sa.Column('inail', sa.String(length=256), nullable=True),
    sa.Column('cedile', sa.String(length=256), nullable=True),
    sa.Column('cedile_prov', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id_esecutore'),
    schema='sue'
    )
    op.create_index(op.f('ix_sue_esecutore_id_esecutore'), 'esecutore', ['id_esecutore'], unique=False, schema='sue')
    op.create_table('fisica',
    sa.Column('app', sa.String(length=256), nullable=True),
    sa.Column('nome', sa.String(length=256), nullable=True),
    sa.Column('cognome', sa.String(length=256), nullable=True),
    sa.Column('cf', sa.String(length=16), nullable=True),
    sa.Column('piva', sa.String(length=11), nullable=True),
    sa.Column('data_nato', sa.Date(), nullable=True),
    sa.Column('comune_nato', sa.String(length=256), nullable=True),
    sa.Column('prov_nato', sa.String(length=2), nullable=True),
    sa.Column('loc_nato', sa.String(length=256), nullable=True),
    sa.Column('codcat_nato', sa.String(length=4), nullable=True),
    sa.Column('cittadinanza', sa.String(length=256), nullable=True),
    sa.Column('sesso', sa.String(length=1), nullable=True),
    sa.Column('comune', sa.String(length=256), nullable=True),
    sa.Column('prov', sa.String(length=2), nullable=True),
    sa.Column('loc', sa.String(length=256), nullable=True),
    sa.Column('cap', sa.String(length=5), nullable=True),
    sa.Column('indirizzo', sa.String(length=256), nullable=True),
    sa.Column('civico', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('pec', sa.String(length=256), nullable=True),
    sa.Column('telefono', sa.String(length=256), nullable=True),
    sa.Column('cellulare', sa.String(length=256), nullable=True),
    sa.Column('fax', sa.String(length=256), nullable=True),
    sa.Column('id_fisica', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_fisica'),
    schema='sue'
    )
    op.create_index(op.f('ix_sue_fisica_id_fisica'), 'fisica', ['id_fisica'], unique=False, schema='sue')
    op.create_table('giuridica',
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('pec', sa.String(length=256), nullable=True),
    sa.Column('telefono', sa.String(length=256), nullable=True),
    sa.Column('cellulare', sa.String(length=256), nullable=True),
    sa.Column('fax', sa.String(length=256), nullable=True),
    sa.Column('id_giuridica', sa.Integer(), nullable=False),
    sa.Column('denominazione', sa.String(length=256), nullable=True),
    sa.Column('cf', sa.String(length=16), nullable=True),
    sa.Column('piva', sa.String(length=11), nullable=True),
    sa.Column('comune', sa.String(length=256), nullable=True),
    sa.Column('prov', sa.String(length=2), nullable=True),
    sa.Column('loc', sa.String(length=256), nullable=True),
    sa.Column('cap', sa.String(length=5), nullable=True),
    sa.Column('indirizzo', sa.String(length=256), nullable=True),
    sa.Column('civico', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id_giuridica'),
    schema='sue'
    )
    op.create_index(op.f('ix_sue_giuridica_id_giuridica'), 'giuridica', ['id_giuridica'], unique=False, schema='sue')
    op.create_table('tecnico',
    sa.Column('app', sa.String(length=256), nullable=True),
    sa.Column('nome', sa.String(length=256), nullable=True),
    sa.Column('cognome', sa.String(length=256), nullable=True),
    sa.Column('cf', sa.String(length=16), nullable=True),
    sa.Column('piva', sa.String(length=11), nullable=True),
    sa.Column('data_nato', sa.Date(), nullable=True),
    sa.Column('comune_nato', sa.String(length=256), nullable=True),
    sa.Column('prov_nato', sa.String(length=2), nullable=True),
    sa.Column('loc_nato', sa.String(length=256), nullable=True),
    sa.Column('codcat_nato', sa.String(length=4), nullable=True),
    sa.Column('cittadinanza', sa.String(length=256), nullable=True),
    sa.Column('sesso', sa.String(length=1), nullable=True),
    sa.Column('comune', sa.String(length=256), nullable=True),
    sa.Column('prov', sa.String(length=2), nullable=True),
    sa.Column('loc', sa.String(length=256), nullable=True),
    sa.Column('cap', sa.String(length=5), nullable=True),
    sa.Column('indirizzo', sa.String(length=256), nullable=True),
    sa.Column('civico', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('pec', sa.String(length=256), nullable=True),
    sa.Column('telefono', sa.String(length=256), nullable=True),
    sa.Column('cellulare', sa.String(length=256), nullable=True),
    sa.Column('fax', sa.String(length=256), nullable=True),
    sa.Column('id_tecnico', sa.Integer(), nullable=False),
    sa.Column('denominazione', sa.String(length=256), nullable=True),
    sa.Column('sede_comune', sa.String(length=256), nullable=True),
    sa.Column('sede_prov', sa.String(length=2), nullable=True),
    sa.Column('sede_cap', sa.String(length=5), nullable=True),
    sa.Column('sede_indirizzo', sa.String(length=256), nullable=True),
    sa.Column('sede_civico', sa.String(length=50), nullable=True),
    sa.Column('albo', sa.String(length=256), nullable=True),
    sa.Column('albo_numero', sa.String(length=256), nullable=True),
    sa.Column('albo_prov', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id_tecnico'),
    schema='sue'
    )
    op.create_index(op.f('ix_sue_tecnico_id_tecnico'), 'tecnico', ['id_tecnico'], unique=False, schema='sue')
    op.create_table('istanza',
    sa.Column('id_istanza', sa.Integer(), nullable=False),
    sa.Column('id_pratica', sa.Integer(), nullable=True),
    sa.Column('anno_istanza', sa.Integer(), nullable=False),
    sa.Column('data_creazione', sa.Date(), nullable=False),
    sa.Column('data_presentazione', sa.Date(), nullable=True),
    sa.Column('tipo_istanza', sa.String(length=256), nullable=False),
    sa.Column('delegato_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['delegato_id'], ['sue.fisica.id_fisica'], ),
    sa.PrimaryKeyConstraint('id_istanza'),
    schema='sue'
    )
    op.create_index(op.f('ix_sue_istanza_id_istanza'), 'istanza', ['id_istanza'], unique=False, schema='sue')
    op.create_index(op.f('ix_sue_istanza_id_pratica'), 'istanza', ['id_pratica'], unique=False, schema='sue')
    op.create_table('civici',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_istanza', sa.Integer(), nullable=True),
    sa.Column('id_via', sa.Integer(), nullable=True),
    sa.Column('via', sa.String(length=256), nullable=True),
    sa.Column('civico', sa.String(length=50), nullable=True),
    sa.Column('note', sa.String(length=256), nullable=True),
    sa.Column('geom', Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['id_istanza'], ['sue.istanza.id_istanza'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='sue'
    )
    op.create_index(op.f('ix_sue_civici_id'), 'civici', ['id'], unique=False, schema='sue')
    op.create_table('esecutori',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_istanza', sa.Integer(), nullable=True),
    sa.Column('id_esecutore', sa.Integer(), nullable=True),
    sa.Column('id_pratica', sa.Integer(), nullable=True),
    sa.Column('sostituito', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_esecutore'], ['sue.esecutore.id_esecutore'], ),
    sa.ForeignKeyConstraint(['id_istanza'], ['sue.istanza.id_istanza'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='sue'
    )
    op.create_index(op.f('ix_sue_esecutori_id'), 'esecutori', ['id'], unique=False, schema='sue')
    op.create_table('nct',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_istanza', sa.Integer(), nullable=True),
    sa.Column('sezione', sa.String(length=30), nullable=True),
    sa.Column('foglio', sa.String(length=8), nullable=True),
    sa.Column('mappale', sa.String(length=8), nullable=True),
    sa.Column('note', sa.String(length=256), nullable=True),
    sa.Column('geom', Geometry(geometry_type='POLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['id_istanza'], ['sue.istanza.id_istanza'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='sue'
    )
    op.create_index(op.f('ix_sue_nct_id'), 'nct', ['id'], unique=False, schema='sue')
    op.create_table('richiedenti',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_istanza', sa.Integer(), nullable=True),
    sa.Column('id_fisica', sa.Integer(), nullable=True),
    sa.Column('id_giuridica', sa.Integer(), nullable=True),
    sa.Column('id_condominio', sa.Integer(), nullable=True),
    sa.Column('fisica_ruolo', sa.String(length=256), nullable=True),
    sa.Column('giuridica_ruolo', sa.String(length=256), nullable=True),
    sa.Column('id_pratica', sa.Integer(), nullable=True),
    sa.Column('sostituito', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_condominio'], ['sue.condominio.id_condominio'], ),
    sa.ForeignKeyConstraint(['id_fisica'], ['sue.fisica.id_fisica'], ),
    sa.ForeignKeyConstraint(['id_giuridica'], ['sue.giuridica.id_giuridica'], ),
    sa.ForeignKeyConstraint(['id_istanza'], ['sue.istanza.id_istanza'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='sue'
    )
    op.create_index(op.f('ix_sue_richiedenti_id'), 'richiedenti', ['id'], unique=False, schema='sue')
    op.create_table('tecnici',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_istanza', sa.Integer(), nullable=True),
    sa.Column('id_tecnico', sa.Integer(), nullable=True),
    sa.Column('tecnico_ruolo', sa.String(length=256), nullable=True),
    sa.Column('data_incarico', sa.Date(), nullable=True),
    sa.Column('id_pratica', sa.Integer(), nullable=True),
    sa.Column('sostituito', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_istanza'], ['sue.istanza.id_istanza'], ),
    sa.ForeignKeyConstraint(['id_tecnico'], ['sue.tecnico.id_tecnico'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='sue'
    )
    op.create_index(op.f('ix_sue_tecnici_id'), 'tecnici', ['id'], unique=False, schema='sue')
    op.create_table('uiu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_istanza', sa.Integer(), nullable=True),
    sa.Column('id_civico', sa.Integer(), nullable=True),
    sa.Column('sezione', sa.String(length=30), nullable=True),
    sa.Column('foglio', sa.String(length=80), nullable=True),
    sa.Column('mappale', sa.String(length=80), nullable=True),
    sa.Column('sub', sa.String(length=80), nullable=True),
    sa.Column('interno', sa.String(length=80), nullable=True),
    sa.Column('scala', sa.String(length=80), nullable=True),
    sa.Column('piano', sa.String(length=80), nullable=True),
    sa.Column('vani', sa.String(length=80), nullable=True),
    sa.Column('supeficie', sa.Float(), nullable=True),
    sa.Column('destuso', sa.String(length=80), nullable=True),
    sa.Column('note', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['id_istanza'], ['sue.istanza.id_istanza'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='sue'
    )
    op.create_index(op.f('ix_sue_uiu_id'), 'uiu', ['id'], unique=False, schema='sue')
    '''
    op.drop_table('project_users')
    op.drop_table('ItemDetail')
    op.drop_table('Item')
    op.drop_table('users')
    op.drop_table('Detail')
    op.drop_table('projects')
    '''
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('projects_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='projects_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('Detail',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Detail_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('value', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Detail_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('users_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('Item',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Item_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Item_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('ItemDetail',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"ItemDetail_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('itemId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('detailId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('endDate', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['detailId'], ['Detail.id'], name='ItemDetail_detailId_fkey'),
    sa.ForeignKeyConstraint(['itemId'], ['Item.id'], name='ItemDetail_itemId_fkey'),
    sa.PrimaryKeyConstraint('id', name='ItemDetail_pkey')
    )
    op.create_table('project_users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='project_users_project_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='project_users_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='project_users_pkey')
    )
    op.drop_index(op.f('ix_sue_uiu_id'), table_name='uiu', schema='sue')
    op.drop_table('uiu', schema='sue')
    op.drop_index(op.f('ix_sue_tecnici_id'), table_name='tecnici', schema='sue')
    op.drop_table('tecnici', schema='sue')
    op.drop_index(op.f('ix_sue_richiedenti_id'), table_name='richiedenti', schema='sue')
    op.drop_table('richiedenti', schema='sue')
    op.drop_index(op.f('ix_sue_nct_id'), table_name='nct', schema='sue')
    op.drop_table('nct', schema='sue')
    op.drop_index(op.f('ix_sue_esecutori_id'), table_name='esecutori', schema='sue')
    op.drop_table('esecutori', schema='sue')
    op.drop_index(op.f('ix_sue_civici_id'), table_name='civici', schema='sue')
    op.drop_table('civici', schema='sue')
    op.drop_index(op.f('ix_sue_istanza_id_pratica'), table_name='istanza', schema='sue')
    op.drop_index(op.f('ix_sue_istanza_id_istanza'), table_name='istanza', schema='sue')
    op.drop_table('istanza', schema='sue')
    op.drop_index(op.f('ix_sue_tecnico_id_tecnico'), table_name='tecnico', schema='sue')
    op.drop_table('tecnico', schema='sue')
    op.drop_index(op.f('ix_sue_giuridica_id_giuridica'), table_name='giuridica', schema='sue')
    op.drop_table('giuridica', schema='sue')
    op.drop_index(op.f('ix_sue_fisica_id_fisica'), table_name='fisica', schema='sue')
    op.drop_table('fisica', schema='sue')
    op.drop_index(op.f('ix_sue_esecutore_id_esecutore'), table_name='esecutore', schema='sue')
    op.drop_table('esecutore', schema='sue')
    op.drop_index(op.f('ix_sue_condominio_id_condominio'), table_name='condominio', schema='sue')
    op.drop_table('condominio', schema='sue')
    # ### end Alembic commands ###
