"""e questo

Revision ID: 975f772256e3
Revises: 97735f664422
Create Date: 2022-05-07 11:50:56.680182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '975f772256e3'
down_revision = '97735f664422'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=256), nullable=True),
    sa.Column('surname', sa.String(length=256), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='per_user'
    )
    op.create_index(op.f('ix_per_user_user_email'), 'user', ['email'], unique=True, schema='per_user')
    op.create_index(op.f('ix_per_user_user_full_name'), 'user', ['full_name'], unique=False, schema='per_user')
    op.create_index(op.f('ix_per_user_user_id'), 'user', ['id'], unique=False, schema='per_user')
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['per_user.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='per_user'
    )
    op.create_index(op.f('ix_per_user_item_description'), 'item', ['description'], unique=False, schema='per_user')
    op.create_index(op.f('ix_per_user_item_id'), 'item', ['id'], unique=False, schema='per_user')
    op.create_index(op.f('ix_per_user_item_title'), 'item', ['title'], unique=False, schema='per_user')
    op.create_table('recipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=256), nullable=False),
    sa.Column('url', sa.String(length=256), nullable=True),
    sa.Column('source', sa.String(length=256), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['per_user.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='per_user'
    )
    op.create_index(op.f('ix_per_user_recipe_id'), 'recipe', ['id'], unique=False, schema='per_user')
    op.create_index(op.f('ix_per_user_recipe_url'), 'recipe', ['url'], unique=False, schema='per_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_per_user_recipe_url'), table_name='recipe', schema='per_user')
    op.drop_index(op.f('ix_per_user_recipe_id'), table_name='recipe', schema='per_user')
    op.drop_table('recipe', schema='per_user')
    op.drop_index(op.f('ix_per_user_item_title'), table_name='item', schema='per_user')
    op.drop_index(op.f('ix_per_user_item_id'), table_name='item', schema='per_user')
    op.drop_index(op.f('ix_per_user_item_description'), table_name='item', schema='per_user')
    op.drop_table('item', schema='per_user')
    op.drop_index(op.f('ix_per_user_user_id'), table_name='user', schema='per_user')
    op.drop_index(op.f('ix_per_user_user_full_name'), table_name='user', schema='per_user')
    op.drop_index(op.f('ix_per_user_user_email'), table_name='user', schema='per_user')
    op.drop_table('user', schema='per_user')
    # ### end Alembic commands ###
